#!/bin/bash

if sudo ip addr del 192.168.1.5/24 dev wlan0; then
	echo "Successfully unassigned"
	if echo "passive" > /tmp/mystate; then
	exit 0
	else
	exit 1
	fi
elif [ $? -eq 2 ]; then
	echo "Exit code was 2. Means there was nothing to remove. Aleady unassigned"
	if echo "passive" > /tmp/mystate; then
	exit 0
	else
	exit 1
	fi
else
	echo "Couldn't unassign"
	exit 1
fi

